#!/bin/bash

# DMT SYSTEM APPS and DMT USER APPS deps
# ⚠️ keep this file in sync with dmt_apps/package.json

declare -a List=(
  "core/node/common"
  "core/node/notify"
  "core/node/search"
  "core/node/connectome/src/client connectome"
  "core/node/connectome/src/stores connectome-stores"
  "core/node/connectome-next connectome-next"
)
