#!/bin/bash

source .bash_util

target="../etc/.bash_aliases_bundle"
target_slim="../etc/.bash_aliases_slim"

VERSION=$(cat ../.version)

cat > "$target_slim" <<EOF
#!/bin/bash

#
#                      DMT ALIASES
#                 _
#             .__(.)< (v${VERSION})
#              \___)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~ WARNING: CHANGES TO THIS FILE WILL BE LOST (FILE IS COMPILED) ~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EOF

echo >> "$target_slim"

cat .bash_util .bash_fs .bash_general .bash_git >> "$target_slim"


cat "$target_slim" > "$target"

cat >> "$target" <<EOF


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~ 💡🚀🎸 FULL EDITION ~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EOF

cat .bash_core_helpers .bash_networking .bash_devices .bash_search .bash_music .bash_dep .bash_update .bash_dmt >> "$target"

printf "${GREEN}* Generating ${CYAN}${target} ${GREEN}on ${CYAN}$(hostname)${NC}\n"

# include staging if exists
# this is never deployed outside of development environment, we have .bash_temp for that
if [ -f .bash_staging ]; then
  printf "${GRAY} -- included .bash_staging${NC}\n"
  cat .bash_staging >> "$target"
fi

printf "${GREEN}* done${NC}\n"

