#!/bin/bash

source .bash_util

target="../etc/.bash_aliases_bundle"

VERSION=$(cat ../.version)

cat > "$target" <<EOF
#!/bin/bash

# DMT ALIASES
#
# WARNING: CHANGES TO THIS FILE WILL BE LOST (FILE IS COMPILED)
# Version ${VERSION}
#
#                                         ,....,.
#                                           ..''   .'
#                                        .'"       |
#                                     .''          \
#                                  .''              \.
#                                .'                  .".,
#                              ,:'             ..,'"'   '...,..::/"".....
#                            /'"          .,'"'  .,',:,'""'         .,''
#                          ,'.'      .,'"' ..,''' ""         .'   ."'
#                        ,'  \, ..,''  .,''. ..,'""        ./   ."
#                      ."     .,"  .,'".,"'./           ..''   /
#                     ,'    .'  ./'.,"'  .'  "'     ." '.     /
#                   .'   ./' ./"."\,..,''     '" ../,     ,  |
#                  ,   ./' .'./'|/     ............        ',|
#                 /   /' ,'.".,'""\..... '""""""""'  .::/'.., |
#                /  ." ,' ':\ """  |  ,      ''          '""   \
#               /  /'.''. |:::::::""' ,' ' ''. ".,.,  """'    .""
#              | ." /.,":. ""..,   "\'.."'..  ;"'  '\.'"""  ."
#              | \.:\.    '""./\ \  | ' '" .,"".           /
#              / \'   '"..     ", \  \,',     "'..  .,     '
#             /.'",''..,  '\,   '\ ". '\'.,     , "'. "'.,|
#            .,'        '". ',    \ '.".. ''../'      "" __\
#            '             \,',    \  '.'\..,  ","'  .'"
#                          |  |    '| ,\""'\/.  |  ."
#             ."          .|  .    / / ./'. '.".' /'
#             /'        ..|':"""\././  /   "  '/\.'
#            //  ./  .'"    /' ./'.' .'  | ..,  ':|
#          ./:  ,/   |",   ' ."'  :  '   |    .../:,
#         .'.'.\/   /.'           ''  .,   ..\'
#       .,\.\".'   /"    ,"' \...,      "\.\| ",
#      /    ./""""'   ..:    ',|  "".,     '\  ',
#   .,' "'   \|     "".'".    '/  .| '\.     ", '\
#  /          \.    ../,   "./ '\ |'  \/"" '".'\  \
# /   '\\:.   \,"\::'  ./""'    ./|  .'     .'"/| '|
# ' ,"\:"/"""  /'  ."\'  .., |:| .| |'    .'' .\|  ',
# |/  / /'    .'| /  |. \,    /'"/. |  |:\..," .||  \
# '' /.'      //\|'  '\/\:.   :,/"'::.  ,   ..::'|  |
#             ||'/,    '\\/"\ '/|    '\ '"::::"| || .
#             || \\       "".   ...,  '.  \\...| |' |
#             ||  "\,         .".\, ". ', | \  '||  |
#              '              |\|'|\/.''\ | |\  ||  |
#                             ||\/"/| '\, ., / / /  ,
#                              ' \  "   '"  / / .' /
#                                 '      .'".' .' /
#        -hrr-                      ..'"'.." ." ."
#                               .,"":.'""..'" ."
#                          .,:'"'"'  .'"  ..'"
#                        ." ."'..'""...,"'
#                     .." "    , ""'
#                    /  . :/"'
#                  .'  :/'
#                 /  /'
#                / .'
#               / '
#              /.'
#              '
#           _
#       .__(.)< (MEOW)
#        \___)
#  ~~~~~~~~~~~~~~~~~~
EOF

#echo "# Produced on $(date)" >> "$target"
echo >> "$target"

cat .bash_util .bash_fs .bash_general .bash_core_helpers .bash_networking .bash_devices .bash_search .bash_music .bash_git .bash_dep .bash_update .bash_dmt >> "$target"

printf "${GREEN}* Generating ${CYAN}${target} ${GREEN}on ${CYAN}$(hostname)${NC}\n"

# include staging if exists
# this is never deployed outside of development environment, we have .bash_temp for that
if [ -f .bash_staging ]; then
  printf "${GRAY} -- included .bash_staging${NC}\n"
  cat .bash_staging >> "$target"
fi

printf "${GREEN}* done${NC}\n"

