#!/bin/bash

source "./shell/.bash_util"
source "./shell/.bash_dmt_vars"
source "./shell/.bash_general"
source "./shell/.bash_networking"
source "./shell/.bash_devices"
source "./shell/.bash_dep"
source "./shell/.bash_update"

FROM_DMT_INSTALL=false
if [ "$1" == "from-dmt-install" ]; then
  FROM_DMT_INSTALL=true
  shift
fi

arg="$1"

if [ "$arg" == "--help" ] || [  "$arg" == "-h" ]; then
  printf "${MAGENTA}∞ DMT ∞ ${CYAN}v$(cat "$DMT_PATH/.version")${NC}\n"
  echo
  printf "${WHITE}Install or update ${MAGENTA}.dmt${NC} scripts and shortcuts on this or any remote ${CYAN}Linux / macOS ${NC}machine (by using ssh).\n"
  echo
  printf "${YELLOW}Usage:${NC}\n"

  if $FROM_DMT_INSTALL; then
    printf "${GREEN}dmt install user@host ${GRAY}installs on user@host${NC}\n"
  else
    printf "${GREEN}$0${GRAY} link-installs current directory on this device${NC}\n"
    printf "${GREEN}$0 user@host ${GRAY}installs on user@host, shortcut ${GREEN}$0 ap ${GRAY}installs on ${DMT_AP_DEFAULT_HOST}${NC}\n"
  fi

  exit
fi

DMT_BASH_PATH="$HOME/.dmt/shell"

function compile {
  local cwd="`pwd`"
  cd "$DMT_BASH_PATH"
  ./compile
  cd "$cwd"
}

if [ -z "$arg" ] || [ "$arg" == "full" ]; then # install here

    COMPILED_BASH_ALIASES="$HOME/.dmt/etc/.bash_aliases_bundle"

    compile

    if [ ! -f "$COMPILED_BASH_ALIASES" ]; then
      printf "${RED}Error: compilation was supposed to produce $COMPILED_BASH_ALIASES${NC}\n"
      exit
    fi

    mkdir -p "$DMT_STATE"
    mkdir -p "$DMT_PATH/log"

    if [ ! -d "$DMT_PATH/user" ] && [ -d "$DMT_PATH/etc/sample_user" ]; then
      cp -r "$DMT_PATH/etc/sample_user" "$DMT_PATH"
      mv "$DMT_PATH/sample_user" "$DMT_PATH/user"
      cwd="`pwd`"
      cd "$DMT_PATH/user/devices"
      ln -s "dmt-new" "this"
      cd "$cwd"
    fi

    if [ -f "$HOME/.bash_aliases" ] || [ -L "$HOME/.bash_aliases" ]; then # -L : we check for broken symlink (-f would return true for working symlink but not for a broken one)
      if [ -f "$HOME/.bash_aliases" ] && [ "$(head -3 "$HOME/.bash_aliases" | tail -1)" == "# DMT ALIASES" ]; then
        rm "$HOME/.bash_aliases"
      else
        mv "$HOME/.bash_aliases" "$HOME/.bash_aliases-backup-by-dmt"
        #printf "\n${GRAY}Backed up $HOME/.bash_aliases → $HOME/.bash_aliases-backup-by-dmt${NC}\n\n"
      fi
    fi

    ln -s "$COMPILED_BASH_ALIASES" "$HOME/.bash_aliases"

    # run after-install (=after-update) hooks

    # general deploy hooks -- all devices
    after_update_hook="$HOME/.dmt/etc/deploy_hooks/after-update"
    if [ -f "$after_update_hook" ]; then
      "$after_update_hook" > /dev/null 2>&1 # redirected to /dev/null because we get ws exception if dmt-proc is not running when trying to restart gui by sending a websocket message
    fi

    # (possibly defined) for each particular device
    after_update_hook="$HOME/.dmt/user/devices/this/after-update"
    if [ -f "$after_update_hook" ]; then
      "$after_update_hook"
    fi

    echo

    printf "${YELLOW}Congrats!${NC} ${MAGENTA}∞ DMT ∞${NC} installed on ${CYAN}$(hostname) ${GRAY}(you may need to reload the terminal tab)${NC}\n"

    if [ ! -d "$DMT_PATH/user" ]; then
      echo
      printf "${GREEN}~/.dmt/user ${CYAN}directory was not present, created a sample one from ${GREEN}~/.dmt/etc/sample_user${NC}\n"
      cp -r "$DMT_PATH/etc/sample_user" "$DMT_PATH/user"

      printf "${YELLOW}Identifying this device as ${CYAN}~/.dmt/user/devices/my_computer${NC} (you can use ${GREEN}dmt device select${NC} to adjust)\n"
      cwd="`pwd`"
      cd "$DMT_PATH/user/devices"
      ln -s my_computer this
      cd "$cwd"
    fi

    echo
    printf "Enter ${GREEN}dmt help${NC} to start. ${YELLOW}If it doesn't work, try ${GRAY}source ~/.bash_aliases ${YELLOW}first.${NC}\n\n"
    printf "${GRAY}Project website — ${MAGENTA}dmt-system.com${NC}\n"

    # printf "Enter ${GREEN}dmt help${NC} to start. ${YELLOW}If it doesn't work, try ${MAGENTA}source ~/.bash_aliases ${YELLOW}first.${NC}\n\n"
    # printf "${GRAY}If this works, then try to log out of terminal and back in.${NC}\n"
    # printf "${GRAY}If it still works, ${GREEN}then everything is set up correctly.${NC}\n"
    # printf "${GRAY}If not, read the docs at ${CYAN}https://github.com/uniqpath/dmt/blob/master/INSTALL.md${NC}\n"

    . "$HOME/.bash_aliases"

else # clone to and install on remote device

    host="$arg"

    if [ "$host" == "ap" ]; then
      host="$DMT_AP_DEFAULT_HOST"
      ssh_port=22
    else
      matching_host=''
      ssh_port=''
      get_full_host matching_host ssh_port "$host"
      if [ $? -ne 1 ]; then # not error
        host="$matching_host"
      fi
    fi

    if [ -z "$host" ]; then
      printf "${RED}Host not known${NC}\n"
      return
    fi

    target="${host}:.dmt"

    printf "${CYAN}Installing on ${YELLOW}$host:$ssh_port${NC}\n"

    dirsync --port $ssh_port ~/.dmt "$target"

    remote --silent -h "$host" --port "$ssh_port" "cd ~/.dmt; ./install"

fi
