#!/bin/bash

# DEFINE COLORS
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\e[0;36m'
MAGENTA='\033[0;35m'
GRAY='\e[1;30m'
NC='\033[0m' # No Color

if [ "$EUID" -ne 0 ]
  then printf "${RED}Must be root${NC}\n"
  exit
fi

if [ -z "$1" ] || [ "$1" == '-h' ]; then
  printf "${YELLOW}Usage:${NC}\n"
  printf "${GREEN}tape_backup [dir]${NC} ${GRAY}starts backing up all subdirectories (but not files directly in that directory!) on the first tape until we run out of space, index of backed up files is saved into TapeIndex${NC}\n"
  printf "${GREEN}tape_backup --diff [dir]${NC} ${GRAY}show directories that are not backed up yet${NC}\n"
  printf "${GREEN}tape_backup --continue [index_file] [dir]${NC} ${GRAY}continue on partially filled tape in case backup was interrupted${NC}\n"
  printf "${GREEN}tape_backup --next-tape [index_file] [dir]${NC} ${GRAY}start backing up on the new tape, reads prior progress from given index file which must include content of ALL previous tapes (concatenate manually!)${NC}\n"
  exit
fi

if [ "$1" == "--continue" ]; then
  continue=true
  index_file="$2"
  shift
  shift
else
  continue=false
fi

if [ "$1" == "--next-tape" ]; then
  nexttape=true
  index_file="$2"
  shift
  shift
else
  nexttape=false
fi

dir="$1"

cwd="`pwd`"
cd "$dir"

if $continue || $nexttape; then
  if [ -z "$index_file" ] || [ ! -f "$index_file" ]; then
    printf "${RED}Index file not given or missing. Please specify it using absolute path...${NC}\n"
    exit
  fi
fi

IFS=$'\n'

if $continue; then
  pos=$(cat "$index_file" | wc -l)
  #todo: test if it works if there is no this further last file
  printf "${YELLOW}Positioning the tape for continuation${NC}\n"
  time sudo mt -f /dev/nst0 asf "$pos"
  sudo mt -f /dev/nst0 status
else
  printf "${YELLOW}Rewinding tape ...${NC}"
  time mt -f /dev/st0 rewind
fi

dirlist=($(find . -maxdepth 1 -type d ! -path . -or -type l | sed "s/^\.\///" | sort))
num_dirs="${#dirlist[@]}"

printf "${MAGENTA}Backing up ${num_dirs} directories...${NC}\n\n"

INDEX_FILE="/home/eclipse/Syncbox/TapeIndex/Index $(date '+%Y-%m-%d %H:%M').txt"

count=0

for dir in ${dirlist[@]} ; do
  msg="${MAGENTA}${count}. ${YELLOW}${dir}${NC}"
  count=$(($count+1))

  if $continue || $nexttape; then
    match=$(cat "$index_file" | grep "^${dir}$" | wc -l)
    if [ $match -eq 1 ]; then
      #printf "${msg}"
      printf "${GRAY}Skipping:${NC} ${msg}\n"
    else
      printf "${GREEN}Backing up:${NC} ${msg}\n"
      time sudo tar -b 2048 -cf /dev/nst0 "$dir"

      if [ $? -eq 0 ]; then
        echo "$dir" >> "$INDEX_FILE"
      else
        printf "${RED}Backup command returned error (full tape?)${NC}\n"
        exit
      fi

      printf "${GREEN}Archived ${dir}${NC}\n\n"
    fi
  else
    printf "${GREEN}Backing up:${NC} ${msg}\n"

    # -h
    # -h, --dereference
    # don't archive symlinks; archive the files they point to
    time sudo tar -b 2048 -cf /dev/nst0 "$dir"

    if [ $? -eq 0 ]; then
      echo "$dir" >> "$INDEX_FILE"
    else
      printf "${RED}Backup command returned error (full tape?)${NC}\n"
      exit
    fi
  fi

done

unset IFS
cd "$cwd"
