#!/bin/bash

mkdir -p ~/.dmt/user/engine; cd $_

if [ -d _dmt_deps ]; then
  rm -rf _dmt_deps
fi

mkdir _dmt_deps; cd $_

declare -a List=(
  "core/node/common ."
  "core/node/notify ."
  "core/node/iot ."
  "core/node/connectome/src/client connectome"
  "core/node/connectome/src/next connectome-next"
  "core/node/connectome/src/server connectome-server"
  "core/node/connectome/src/stores connectome-stores"
)

for entry in "${List[@]}"; do
  parts=($entry)

  ln -s "../../../${parts[0]}" ${parts[1]}
done
