#!/bin/bash

mkdir -p ~/.dmt/apps; cd $_

if [ -d _dmt_deps ]; then
 rm -rf _dmt_deps
fi

mkdir -p ~/.dmt/user/apps; cd $_

if [ -d _dmt_deps ]; then
  rm -rf _dmt_deps
fi

declare -a List=(
  "core/node/common ."
  "core/node/notify ."
  "core/node/search ."
  "core/node/connectome/src/client connectome"
  "core/node/connectome/src/stores connectome-stores"
  "core/node/connectome-next connectome-next"
)

for entry in "${List[@]}"; do
  parts=($entry)

  mkdir -p ~/.dmt/apps/_dmt_deps; cd $_
  ln -s "../../${parts[0]}" ${parts[1]}

  mkdir -p ~/.dmt/user/apps/_dmt_deps; cd $_
  ln -s "../../../${parts[0]}" ${parts[1]}
done
