#!/bin/bash

DMT_APPS="$HOME/.dmt/apps"
DMT_USER_APPS="$HOME/.dmt/user/apps"

# bugfix! remove soon -- some previous version of this script copied package.json into ~/.dmt/user/apps FILE
# or maybe keep this, doesn't hurt if indeed someone creates an `apps` file by mistake (low chance but if they do, it screws up everything :)
if [ -f "$DMT_APPS" ]; then
  rm "$DMT_APPS"
fi
if [ -f "$DMT_USER_APPS" ]; then
  rm "$DMT_USER_APPS"
fi

mkdir -p "$DMT_APPS"
mkdir -p "$DMT_USER_APPS"

# a) create _dmt_deps with symlinks to dmt node_modules
# b) copy related package.json into ~/.dmt/apps

if [ -f "$DMT_APPS/package.json" ] && [ -d "$DMT_APPS/_dmt_deps" ]; then
  if ! diff ./package.json "$DMT_APPS/package.json" > /dev/null
  then
    cp package.json "$DMT_APPS"
    ./create_symlinks_for_apps
  fi
else
  cp package.json "$DMT_APPS"
  ./create_symlinks_for_apps
fi

# todo: make more effective, don't call create_symlinks_for_apps twice?

if [ -f "$DMT_USER_APPS/package.json" ] && [ -d "$DMT_USER_APPS/_dmt_deps" ]; then
  if ! diff ./package.json "$DMT_USER_APPS/package.json" > /dev/null
  then
    cp package.json "$DMT_USER_APPS"
    ./create_symlinks_for_apps
  fi
else
  cp package.json "$DMT_USER_APPS"
  ./create_symlinks_for_apps
fi
