#!/bin/bash

# DMT USER ENGINE deps
# ⚠️ keep this file in sync with:
# - dmt_user_engine/exports.json !
# dmt_apps:
#  - dmt_deps_list
#  - package.json
# ⚠️ don't use .js, this is a DIRECTORY LIST...
# "core/node/common" ✓
# "core/node/common.js" ✖

declare -a List=(
  "core/node/common"
  "core/node/notify"
  "core/node/iot"
  "core/node/connectome/src/client connectome"
  "core/node/connectome/src/server connectome-server"
  "core/node/connectome/src/stores-node connectome-stores"
)
