#!/bin/bash

source ./dmt_apps/dmt_deps_list
source ./helpers/make_symlinks

# dmt system apps
mkdir -p ~/.dmt/apps/_dmt_deps; cd $_
make_symlinks "../../" "${List[@]}"

# dmt user apps
mkdir -p ~/.dmt/user/apps/_dmt_deps; cd $_
make_symlinks "../../../" "${List[@]}"

# dmt device apps
mkdir -p ~/.dmt-here/apps/_dmt_deps; cd $_
make_symlinks "../../../.dmt/" "${List[@]}"
