#!/bin/bash

DMT_APPS="$HOME/.dmt/apps"
DMT_USER_APPS="$HOME/.dmt/user/apps"
DMT_DEVICE_APPS="$HOME/.dmt-here/apps"

mkdir -p "$DMT_APPS"
mkdir -p "$DMT_USER_APPS"
mkdir -p "$DMT_DEVICE_APPS"

# a) create _dmt_deps with symlinks to dmt node_modules
./create_symlinks_apps

# b) copy related package.json into ~/.dmt/apps

if [ -f "$DMT_APPS/package.json" ]; then
  if ! diff ./dmt_apps/package.json "$DMT_APPS/package.json" > /dev/null
  then
    cp ./dmt_apps/package.json "$DMT_APPS"
  fi
else
  cp ./dmt_apps/package.json "$DMT_APPS"
fi

if [ -f "$DMT_USER_APPS/package.json" ]; then
  if ! diff ./dmt_apps/package.json "$DMT_USER_APPS/package.json" > /dev/null
  then
    cp ./dmt_apps/package.json "$DMT_USER_APPS"
  fi
else
  cp ./dmt_apps/package.json "$DMT_USER_APPS"
fi

if [ -f "$DMT_DEVICE_APPS/package.json" ]; then
  if ! diff ./dmt_apps/package.json "$DMT_DEVICE_APPS/package.json" > /dev/null
  then
    cp ./dmt_apps/package.json "$DMT_DEVICE_APPS"
  fi
else
  cp ./dmt_apps/package.json "$DMT_DEVICE_APPS"
fi
