#!/bin/bash

mkdir -p ~/.dmt/apps; cd $_

if [ -d _dmt_deps ]; then
  rm -rf _dmt_deps
fi

mkdir _dmt_deps; cd $_

ln -s ../../core/node/connectome/src/client connectome
ln -s ../../core/node/connectome/src/stores connectome-stores

ln -s ../../core/node/connectome-next connectome-next

ln -s ../../core/node/bridge .
ln -s ../../core/node/search .
ln -s ../../core/node/notify .

