#!/bin/bash

# SETUP:

# linux:
# crontab -e
# @reboot bash -ic ~/.dmt/etc/onboot/onboot

# macOS:
# cp ~/.dmt/etc/onboot/macos-launchagent-script/dmt-controller.plist ~/Library/LaunchAgents

source ~/.dmt/shell/.bash_custom

~/.dmt/etc/onboot/daemons start #_or_restart

if [ -f ~/.dmt/user/devices/this/onboot ]; then
  ~/.dmt/user/devices/this/onboot
fi
