#!/bin/bash

DMT_NODE_CORE="$HOME/.dmt/core/node"

if [ -d "$DMT_NODE_CORE" ]; then
  # there are some other places that should be updated if nodejs flags change! find and replace ...
  DMT_NODEJS_EXEC="node --unhandled-rejections=strict"

  # use bun if available
  # if command -v bun >/dev/null 2>&1; then
  #   #printf "✅ Using ${GREEN}bun${NC}\n"
  #   DMT_NODEJS_EXEC="node --unhandled-rejections=strict"
  # else
  #   DMT_NODEJS_EXEC="node --unhandled-rejections=strict"
  # fi

  $DMT_NODEJS_EXEC "${DMT_NODE_CORE}/gui/cli/gui.js" reload
fi
