<script>
  import JSONTree from 'svelte-json-tree';
  export let swarm;
</script>

{#if swarm}

  <div class="data">

    {#if swarm}
      <JSONTree value={swarm} />
    {/if}

    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF
    ASDFASDFKJASDFKJADSFKASDJFKASDKF

  </div>

{/if}

<style>

.data {
  background-color: white;
}

</style>
