#!/bin/bash

function parse_dep_aspect() {
  local dep="$3"
  local _dmt_dep_without_aspect=''
  local _aspect=''

  arr=(${dep/\// }) # split on /
  _aspect=''
  if [ ${#arr[@]} == 1 ]; then
    _dmt_dep_without_aspect="$arr"
  else
    _dmt_dep_without_aspect="${arr[@]:1}" # take everything except first el
    _aspect="${arr[0]}"
  fi

  eval "$1='${_dmt_dep_without_aspect}'"
  eval "$2='${_aspect}'"
}


