language: rust
matrix:
  include:
    - os: linux
      rust: 1.23.0
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: nightly
script: ci/script.sh
branches:
  only:
    - master
